### ISSUE TITLE
metaversestandards-glossary/msf-termbase.meta.yaml is missing

### ISSUE THREAD

**Issue by ribose-jeffreylau** [MetaverseStandards/glossary.metaverse-standards.org#1]
This file is required by ci in order to generate the site files.

Related issue: https://github.com/MetaverseStandards/metaversestandards-glossary/issues/2
Corresponding pull request: https://github.com/MetaverseStandards/metaversestandards-glossary/pull/3

After the above issue is fixed, a submodule to `https://github.com/MetaverseStandards/metaversestandards-glossary` needs to be created here so the missing file can be found.

**Comment by allcreatures** [comment]
Thank you. This patch resolved the issue.
