### ISSUE TITLE
breviter is missing, causing CI to fail

### ISSUE THREAD

**Issue by ribose-jeffreylau** [MetaverseStandards/glossary.metaverse-standards.org#3]

**Comment by allcreatures** [comment]
Just added breviter. Oops.

**Comment by ribose-jeffreylau** [comment]
No worries, I think your commit fixes this issue :)

**Comment by allcreatures** [comment]
Apparently not. my user of submodules is week apparently, breviter/data is not pointing to main branch.

**Comment by allcreatures** [comment]
Missing:
/home/runner/work/glossary.metaverse-standards.org/glossary.metaverse-standards.org/breviter/public/db.json

Do I need to do something with breviter locally in order to generate these files?

**Comment by ribose-jeffreylau** [comment]
> Missing: /home/runner/work/glossary.metaverse-standards.org/glossary.metaverse-standards.org/breviter/public/db.json
> 
> Do I need to do something with breviter locally in order to generate these files?

Quick answer: from the look of breviter's package.json, it seems `yarn build` under `breviter/` would generate it.

**Comment by ribose-jeffreylau** [comment]
> Apparently not. my user of submodules is week apparently, breviter/data is not pointing to main branch.

Quite puzzling.  `breviter/data` is a submodule of `breviter`, but it should be taken care of by https://github.com/MetaverseStandardsActions/ci/blob/main/.github/workflows/site-deploy.yml#L103C27-L103C27

**Comment by allcreatures** [comment]
Running git submodule update --remote resolved the branch issue.

**Comment by allcreatures** [comment]
> Quick answer: from the look of breviter's package.json, it seems yarn build under breviter/ would generate it.

Appears this error is more onpoint for the current issue, as it blocks building public/db.json:

```
[breviter] Computing DB concept dataset at data ...[breviter] Loaded concept dataset with 3 entries.
(node:3168) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property 'termid' of 'x' as it is undefined.
    at validateYAML (/home/runner/work/glossary.metaverse-standards.org/glossary.metaverse-
```

**Comment by allcreatures** [comment]
Should I should open a ticket on geolexica/breviter? /cc @strogonoff

**Comment by allcreatures** [comment]
Same error when attempting to run locally:

```
$ yarn cli compute data -o public/db.json
$ ts-node --project tsconfig.bin.json src/cli.ts compute data -o public/db.json
cli handler
[breviter] Computing DB concept dataset at data ...[breviter] Loaded concept dataset with 3 entries.
/Volumes/OOC16/outofcontrol/Code/Github/MetaverseStandardsActions/breviter/src/util/reverseEngine.ts:80
  const {termid, term, eng} = x;
         ^
TypeError: Cannot destructure property 'termid' of 'x' as it is undefined.
    at validateYAML (/Volumes/OOC16/outofcontrol/Code/Github/MetaverseStandardsActions/breviter/src/util/reverseEngine.ts:80:10)
    at /Volumes/OOC16/outofcontrol/Code/Github/MetaverseStandardsActions/breviter/src/util/reverseEngine.ts:43:15
    at Array.map (<anonymous>)
    at buildDatabase (/Volumes/OOC16/outofcontrol/Code/Github/MetaverseStandardsActions/breviter/src/util/reverseEngine.ts:43:6)
    at savePrecomputedDB (/Volumes/OOC16/outofcontrol/Code/Github/MetaverseStandardsActions/breviter/lib/server.ts:38:33)
    at Object.handler (/Volumes/OOC16/outofcontrol/Code/Github/MetaverseStandardsActions/breviter/src/commands/compute.ts:46:20)
    at /Volumes/OOC16/outofcontrol/Code/Github/MetaverseStandardsActions/breviter/node_modules/yargs/build/index.cjs:1:8891
    at j (/Volumes/OOC16/outofcontrol/Code/Github/MetaverseStandardsActions/breviter/node_modules/yargs/build/index.cjs:1:4956)
    at M.handleValidationAndGetResult (/Volumes/OOC16/outofcontrol/Code/Github/MetaverseStandardsActions/breviter/node_modules/yargs/build/index.cjs:1:8860)
    at M.applyMiddlewareAndGetResult (/Volumes/OOC16/outofcontrol/Code/Github/MetaverseStandardsActions/breviter/node_modules/yargs/build/index.cjs:1:9502)
error Command failed with exit code 1.
```

**Comment by allcreatures** [comment]
Switching to geolexica/breviter, does that not build the data submodule from geolexica, which is the ISO data?

**Comment by ribose-jeffreylau** [comment]
@outofcontrol You are right, let me check...

**Comment by allcreatures** [comment]
@ribose-jeffreylau  Loading geolexica/breviter locally and running yarn install;yarn compute does run successfully, but not with our data. Am I not understanding how the submodule is being referenced at build time?

Loading geolexica/breviter locally but, using our data, once again fails This suggests our data is not what is expected, or breviter can't run with the format of something in our data.

**Comment by allcreatures** [comment]
> @outofcontrol You are right, let me check...

Since I sort of mangled my way through generating the paneron dataset, there is a high likelyhood the data is wrong. :)

**Comment by allcreatures** [comment]
Added id: 1 and id :2 to relevant concepts yaml files resolved the issue.

**Comment by allcreatures** [comment]
*sigh* Error is still present when running the entire pipeline.
